# Promise-Async-Await in Node.js

## Async Pattern - Blocking Code
아래와 같이 코드를 작성하고, /about url을 호출하고, 그 이후에 / or 다른 url을 호출하면, 어느 정도 딜레이가 발생하는 것을 확인할 수 있다. 그 이유는 JavaScript는 Single Thread 방식으로 동작하기 때문에 /about 조건문 내부에 있는 반복문에 대한 처리가 끝나야 다음 단계로 넘어갈 수 있기 때문이다. 이러한 상황을 Blocking Code라 생각할 수 있다.

더 쉬운 이해를 위해서 Blocking Code는 식당에서 점원이 하나의 주문을 받고, 주문한 음식이 나오기 전까지 다른 음식 주문을 받지 않는 상황이라 생각하면 된다. 이 경우 주문한 음식에 따라 소요되는 시간이 다르기 때문에, 프로그램이 잘 동작함을 보장하기 어렵다. 그러므로

실제 식당에서 하나의 주문을 받고, 다른 주문을 받아 빨리 나오는 것을 먼저 처리하는 방식으로 동작하는 NonBlocking 방식의 코드 작성법에 대한 학습이 필요하다.
 
```javascript
const http = require("http");

const server = http.createServer((req, res) => {
  if (req.url === "/") {
    res.end("Home Page");
  }

  if (req.url === "/about") {
    // Blocking Code!!

    for (let i = 0; i < 1000; i++) {
      for (let j = 0; j < 1000; j++) {
        console.log(`${i} ${j}`);
      }
    }

    res.end("About Page");
  }

  res.end("Error Page");
});

server.listen(5000, () => {
  console.log("Server is listening on port 5000...");
});
```

## Async Basics
- `Sync` 코드를 먼저 실행시킨다.
- 이벤트 루프는 콜백 대기열의 이벤트가 `call stack`에 대해 이벤트를 실행하는지를 계속해서 확인한다. 실행 준비가 되었다면, 실행하고 그렇지 않다면 바로 다음 줄로 건너띈다.
```javascript
// #1 - Sync
console.log('Before');

// #2 - Async
setTimeout(() => {         
    console.log('This is Async Function')
}, 2000)

// #3 - Sync
console.log('After');

// Result
// Before ==> After ==> This is Async Function
```
- 비동기로 동작하는 `setTimeout` 등과 함수의 리턴 값으로 다수의 비동기 함수를 리턴 값으로 정의하는 경우 코드 가독성이 좋지 않다는 의미에서, `Callback Hell`이라 칭한다.
```javascript
console.log('Before');

getUser(1, (user) => {
    getRepositories(user.gitHubUsername, (repos) => {
        getCommits(repos[0], (commits) => {
            console.log(commits);
        })
    })
})

console.log('After');

function getUser(id, callback) {
    setTimeout(() => {
        console.log('Reading a user from a database...');
        callback({ id: id, gitHubUsername: 'su' })
    }, 2000)
}

function getRepositories(username, callback) {
    setTimeout(() => {
        console.log('Calling GitHub API...');
        callback(['repo1', 'repo2', 'repo3'])
    }, 2000)
}

function getCommits(repo, callback) {
    setTimeout(() => {
        console.log('Calling GitHub API...');
        callback(['commit'])
    }, 2000)
}
```
- `Callback Hell`을 해결하는 첫 번째 방법: `Promise`의 사용
```javascript
console.log('Before');

getUser(1)
    .then(user => getRepositories(user.gitHubUsername))
    .then(repos => getCommits(repos[0]))
    .then(commits => console.log(commits))
    .catch(err => console.log(new Error(err)))


function getUser(id) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Reading a user from a database...');
            resolve({ id: id, gitHubUsername: 'mosh' });
        }, 2000);
    });
}

function getRepositories(username) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Calling GitHub API..');
            resolve(['repo1', 'repo2', 'repo3'])
        }, 2000)
    })
}

function getCommits(repo) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Calling GitHub API...');
            resolve(['commit'])
        }, 2000)
    })
}



console.log('After');
```
- `Promise All`을 활용하는 경우
- `Promise All` -->`In Parallel Structure`
- `Promise All`의 경우 먼저 시작하는 것은 있어도 먼저 시작한 것이 완료되든 안되든 상관없이
- 바로 다음 것으로 넘어가 실행하고 먼저 결과값이 resolve 된 것을 차례로 배열에 담는다.
```javascript
const p1 = new Promise((resolve, reject) => {
    setTimeout(() => {
        console.log('Async Operation 1...');
        resolve(1);
    }, 2000)
})

const p2 = new Promise((resolve, reject) => {
    setTimeout(() => {
        console.log('Async Operation 2...');
        resolve(2);
    })
})


Promise.all([p1, p2])
    .then(result => console.log(result));
```
- `Promise All` 사용 시 오류가 발생하는 경우
- 여기서 주목할 점은 `promise.all`을 사용했을 때 여러 개의 `promise` 중 단 하나라도 에러가 있다면,
`promise.all`은 모든 `promise`에 에러가 있는 것으로 간주한다는 점이다.
```javascript
const p1 = new Promise((resolve, reject) => {
    setTimeout(() => {
        console.log('Async Operation 1...');
        reject(new Error('because something failed!'))
    }, 2000)
})

const p2 = new Promise((resolve, reject) => {
    setTimeout(() => {
        console.log('Async Operation 2...');
        resolve(2);
    }, 2000)
})

Promise.all([p1, p2])
    .then(result => console.log(result))
    .catch(err => console.log('Error', err.message))
```
- 여러 개의 비동기 동작이 거의 동시에 동작을 시작하고 단 하나의 동작이라도 완료가 되는 순간 어떤 행위를 하고 싶은 경우에 어떻게 해야 하는가?
- 이때 우리는 `promise.race`를 이용할 수 있다. 코드로 보자면, 기억하기 쉽게 비동기로 동작하는 함수 중 누가 먼저 `event loop`를 타고 `call stack`으로 올라오는가에 대해 경주하는 것이다.
```javascript
const p1 = new Promise((resolve, reject) => {
    setTimeout(() => {
        console.log('Async Operation 1...');
        resolve(1);
    }, 2000);
})

const p2 = new Promise((resolve, reject) => {
    setTimeout(() => {
        console.log('Asnyc Operation 2...');
        resolve(2);
    }, 1000);
})

Promise.race([p1, p2])
    .then(result => console.log(result))
    .catch(err => console.log('Error', err.message));

/*
promise p1과 p2가 거의 동시에 비동기 동작을 시작했다.
하지만, race를 사용했기 때문에, p1이 동작이 끝나자마자 p1의 resolve 결과만 배열이 아닌 보통 값으로 리턴을 해준다.

즉, race는 여러 개의 promise를 거의 동시에 동작시킬 수 있지만 하나라도 동작이 끝난 promise가 발생하면 모든 promise가 끝이 났다고 간주하고, 가장 먼저 끝이 난 한 동작의 resolve 값을 return해준다 (단, 전제는 성공적으로 오류 없이 동작이 끝이 났을 때).

Result
'Async Operation 1...'
'Async Operation 2...'
2
*/
```
- `Promise`를 활용한 비동기 코드 처리 방식을 요약하면 다음과 같다.
```javascript
getUser(1, (user) => {
    getRepositories(user.gitHubUsername, (repos) => {
        getCommits(repos[0], (commits) => {
            console.log(commits);
        })
    })
});


// Promise-based Approach
getUser(1)
    .then(user => getRepositories(user.gitHubUsername))
    .then(repos => getCommits(repos[0]))
    .then(commits => console.log('Commits', commits))
    .catch(err => console.log('Error', err.message))

function getUser(id) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Reading a user from a database...');
            resolve({ id: id, gitHubUsername: 'su' })
        }, 2000)
    })
}

function getRepositories(username) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Calling GitHub API...');
            resolve(['repo1', 'repo2', 'repo3'])
        }, 2000)
    })
}

function getCommits(repo) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Calling GitHub API...');
            resolve(['commit'])
        }, 2000);
    })
}
```
- `Promise-based approach` 방식을 조금 더 동기적 방식으로 표현할 수 있는 `Syntatical Sugar`를 `Async and Await Approach`라고 부른다.
- 우선 `Await Operator`는 `Promise`를 `return` 해주는 함수에서만 사용이 가능하다.
- 예를 들면, `const a = 비동기 함수`,라고 했을 때 원래 a라는 변수에는 `비동기 함수`가 담길 수 없다
- 하지만 그 앞에 `await operator`를 붙여주면 마치 `비동기 함수`인 것처럼 동작한다.
- 예를 들면, `const user = await 비동기 함수(1)`는 일반 함수와 달리 모든 비동기 함수의 동작이 다 끝날 때까지 기다리고 마치 일반 함수를 호출해 리턴 한 값을 할당하는 것처럼 동작한다.
```javascript
console.log('Before')
const user = await getUser(1);
const repos = await getRepositories(user);
const commits = await getCommits(repos[0]);
console.log(commits);
console.log('After')

function getUser(id) {
    return new Promise((resolve, reject) => {
        // Kick off some async work 
        setTimeout(() => {
            console.log('Reading a user from a database...');
            resolve({ id: id, gitHubUsername: 'mosh' });
        }, 2000);
    });
}

function getRepositories(username) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Calling GitHub API...');
            resolve(['repo1', 'repo2', 'repo3']);
        }, 2000);
    });
}

function getCommits(repo) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Calling GitHub API...');
            resolve(['commit']);
        }, 2000);
    });
}
```
- `await operator`를 사용했을 때의 장점은 우리가 조금 더 `callback`과 `promise`에 비해 읽고 이해하기가 용이하고, 비동기적 동작을 마치 동기적으로 동작하는 것처럼 보여준다는 점이고,
- 하나 더 추가하자면, `promise`에서 사용했던 `then and catch chain`을 사용할 필요가 없다는 점이다.
- 그럼 async는 어디에 사용되는 것인가요? 
  - 우리가 함수 안에서 `await operator`를 사용할 때마다 우리는 이 함수명은 `async modifier`로 꾸며 줘야한다. 
- 위 코드는 현재 `async keyword`가 없이 때문에 동작하지 않는다.
```javascript
function getUser(id) {
    return new Promise((resolve, reject) => {
        // Kick off some async work 
        setTimeout(() => {
            console.log('Reading a user from a database...');
            resolve({ id: id, gitHubUsername: 'mosh' });
        }, 2000);
    });
}

function getRepositories(username) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Calling GitHub API...');
            resolve(['repo1', 'repo2', 'repo3']);
        }, 2000);
    });
}

function getCommits(repo) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Calling GitHub API...');
            resolve(['commit']);
        }, 2000);
    });
}

console.log('Before')

async function displayCommits() {
    const user = await getUser(1);
    const repos = await getRepositories(user);
    const commits = await getCommits(repos[0]);
    console.log(commits);
}

displayCommits();
console.log('After')
```

- 함수 안에 `await`을 사용할 때 `async`를 사용해야 하는 이유
1. 항상 `promise`를 `return` 함을 명시하기 위해.
2. 만일 한 함수가 `Non-Promise`를 리턴해줘도 `async`가 앞에 붙어있으면 `JS Engine`은 자동으로 `return` 해주는 값을 `resolve promise` 감싸서 리턴하는 역할을 한다.
3. `VSCode`에서 `displayCommits()`에 마우스를 대면 `return type`이 `void`라 나온다. 이것은 `promise`를 이미 `return` 하고 난 뒤 어떠한 것도 `return` 할 것이 없기 때문이다.
만일 `return` 값이 `promise`가 아닌 경우 `void`가 아닌 `undefined`이 나온다.

- 요약: `promise`가 있어야먄 `return` 할 것이 없을 때 `void`를 `return` 한다. 하지만, 내부적으로는 `promise-based approach`와 동일하게 동작한다.

- 마지막으로 `async and await`의 경우, `promise`와 같이 `catch/then`을 사용하지 않기 때문에, 오류 검사 시 `try/catch` 문을 대안으로 사용한다.
```javascript
async function displayCommits() {
    try {
        const user = await getUser(1);
        const repos = await getRepositories(user);
        const commits = await getCommits(repos[0]);
        console.log(commits);

    }

    catch (err) {
        console.log('Error', err.message);
    }
}

displayCommits();

function getUser(id) {
    return new Promise((resolve, reject) => {
        // Kick off some async work 
        setTimeout(() => {
            console.log('Reading a user from a database...');
            resolve({ id: id, gitHubUsername: 'mosh' });
        }, 2000);
    });
}
function getRepositories(username) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Calling GitHub API...');
            //      resolve(['repo1', 'repo2', 'repo3']);
            reject(new Error('Could not get the repos'))
        }, 2000);
    });
}
function getCommits(repo) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Calling GitHub API...');
            resolve(['commit']);
        }, 2000);
    });
}

// 결과
// Before
// After
//'Reading a user from a database...'
//'Calling GitHub API...'
// Error Could not get the repos.
```